# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15  # نسخه پیشنهادی PDF
    restart: always
    environment:
      POSTGRES_DB: todolist_db
      POSTGRES_USER: todolist_user
      POSTGRES_PASSWORD: your_secure_password  # تغییر بده
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: